version: '3.8'
services:
  postgres:
    container_name: postgres23
    image: postgres:15
    expose:
      - '5432'
    ports:
      - '5434:5432'
    volumes:
      - /data/postgres1:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - authnet

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin23
    image: dpage/pgadmin4
    ports:
      - '8081:80'
    volumes:
      - /data/pgadmin1:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - authnet

networks:
  authnet:
    driver: bridge
